# Form implementation generated from reading ui file 'Encryptor.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Headinglbel = QtWidgets.QLabel(parent=self.centralwidget)
        self.Headinglbel.setGeometry(QtCore.QRect(10, 10, 781, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Headinglbel.setFont(font)
        self.Headinglbel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Headinglbel.setObjectName("Headinglbel")
        self.enterlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.enterlabel.setGeometry(QtCore.QRect(20, 90, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enterlabel.setFont(font)
        self.enterlabel.setObjectName("enterlabel")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 0, 751, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 60, 751, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(2)
        self.line_2.setMidLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.originalmessage = QtWidgets.QLabel(parent=self.centralwidget)
        self.originalmessage.setGeometry(QtCore.QRect(180, 90, 611, 91))
        self.originalmessage.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.originalmessage.setText("")
        self.originalmessage.setObjectName("originalmessage")
        self.Scrollbutton = QtWidgets.QScrollBar(parent=self.centralwidget)
        self.Scrollbutton.setGeometry(QtCore.QRect(750, 100, 31, 71))
        self.Scrollbutton.setMinimum(1)
        self.Scrollbutton.setMaximum(10)
        self.Scrollbutton.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.Scrollbutton.setObjectName("Scrollbutton")
        self.encryptbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.encryptbutton.setGeometry(QtCore.QRect(350, 200, 131, 51))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(16)
        self.encryptbutton.setFont(font)
        self.encryptbutton.setObjectName("encryptbutton")
        self.Encryptmessage = QtWidgets.QLabel(parent=self.centralwidget)
        self.Encryptmessage.setGeometry(QtCore.QRect(10, 260, 781, 281))
        self.Encryptmessage.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.Encryptmessage.setText("")
        self.Encryptmessage.setObjectName("Encryptmessage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Headinglbel.setText(_translate("MainWindow", "Message Encryption"))
        self.enterlabel.setText(_translate("MainWindow", "Enter Message:"))
        self.encryptbutton.setText(_translate("MainWindow", "Encrypt"))


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.encryptbutton.clicked.connect(self.encrypt_message)
        self.ui.originalmessage.setWordWrap(True)
        self.ui.Encryptmessage.setWordWrap(True)

    def encrypt_message(self):
        text, ok = QtWidgets.QInputDialog.getText(
            self,
            "Enter Message",
            "Type the message to encrypt:"
        )
        if not ok or not text:
            return

        self.ui.originalmessage.setText(text)
        encrypted_text = self.apply_caesar_cipher(text, shift=3)
        self.ui.Encryptmessage.setText(encrypted_text)

    def apply_caesar_cipher(self, message, shift=3):
        lowercase = "".join(chr(i) for i in range(97, 123))
        uppercase = "".join(chr(i) for i in range(65, 91))
        encrypted = ""

        for ch in message:
            if ch in lowercase:
                pos = lowercase.index(ch)
                encrypted += lowercase[(pos + shift) % 26]
            elif ch in uppercase:
                pos = uppercase.index(ch)
                encrypted += uppercase[(pos + shift) % 26]
            else:
                encrypted += ch

        return encrypted


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
