from PyQt6 import QtCore, QtGui, QtWidgets
import random


class Ui_GAME(object):
    def setupUi(self, GAME):
        GAME.setObjectName("GAME")
        GAME.resize(800, 643)
        self.centralwidget = QtWidgets.QWidget(parent=GAME)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 771, 20))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(50)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 771, 20))
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setLineWidth(5)
        self.label_2.setMidLineWidth(50)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(64, 20, 701, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 361, 341))
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 90, 361, 341))
        self.label_5.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.Result = QtWidgets.QLabel(parent=self.centralwidget)
        self.Result.setGeometry(QtCore.QRect(20, 480, 751, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Result.setFont(font)
        self.Result.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.Result.setText("")
        self.Result.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Result.setObjectName("Result")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(380, 90, 31, 341))
        self.label_7.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.label_7.setLineWidth(3)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 100, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(420, 100, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.numlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.numlabel.setGeometry(QtCore.QRect(30, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numlabel.setFont(font)
        self.numlabel.setObjectName("numlabel")
        self.Restart_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Restart_button.setGeometry(QtCore.QRect(10, 540, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Restart_button.setFont(font)
        self.Restart_button.setObjectName("Restart_button")
        self.EXIT_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.EXIT_button.setGeometry(QtCore.QRect(670, 540, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EXIT_button.setFont(font)
        self.EXIT_button.setObjectName("EXIT_button")
        self.RESULTLABEL = QtWidgets.QLabel(parent=self.centralwidget)
        self.RESULTLABEL.setGeometry(QtCore.QRect(30, 445, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RESULTLABEL.setFont(font)
        self.RESULTLABEL.setObjectName("RESULTLABEL")
        self.input1 = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(230, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input1.setFont(font)
        self.input1.setWrapping(False)
        self.input1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input1.setMinimum(1)
        self.input1.setMaximum(6)
        self.input1.setSingleStep(1)
        self.input1.setObjectName("input1")
        self.U1guess = QtWidgets.QPushButton(parent=self.centralwidget)
        self.U1guess.setGeometry(QtCore.QRect(250, 200, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.U1guess.setFont(font)
        self.U1guess.setObjectName("U1guess")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 250, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.system1gen = QtWidgets.QLabel(parent=self.centralwidget)
        self.system1gen.setGeometry(QtCore.QRect(220, 250, 141, 31))
        self.system1gen.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.system1gen.setText("")
        self.system1gen.setObjectName("system1gen")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(30, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Score1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score1.setGeometry(QtCore.QRect(220, 380, 141, 31))
        self.Score1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.Score1.setText("")
        self.Score1.setObjectName("Score1")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(40, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(30, 290, 341, 71))
        self.label_17.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(40, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.match1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.match1.setGeometry(QtCore.QRect(220, 320, 141, 31))
        self.match1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.match1.setText("")
        self.match1.setObjectName("match1")
        self.numlabel2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.numlabel2.setGeometry(QtCore.QRect(420, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numlabel2.setFont(font)
        self.numlabel2.setObjectName("numlabel2")
        self.input2 = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.input2.setGeometry(QtCore.QRect(620, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input2.setFont(font)
        self.input2.setWrapping(False)
        self.input2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input2.setMinimum(1)
        self.input2.setMaximum(6)
        self.input2.setSingleStep(1)
        self.input2.setObjectName("input2")
        self.u2guess = QtWidgets.QPushButton(parent=self.centralwidget)
        self.u2guess.setGeometry(QtCore.QRect(640, 190, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.u2guess.setFont(font)
        self.u2guess.setObjectName("u2guess")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(420, 250, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.system2Gen = QtWidgets.QLabel(parent=self.centralwidget)
        self.system2Gen.setGeometry(QtCore.QRect(610, 250, 141, 31))
        self.system2Gen.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.system2Gen.setText("")
        self.system2Gen.setObjectName("system2Gen")
        self.label_22 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(420, 290, 341, 71))
        self.label_22.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(430, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(420, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.score2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.score2.setGeometry(QtCore.QRect(610, 380, 141, 31))
        self.score2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.score2.setText("")
        self.score2.setObjectName("score2")
        self.label_26 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(430, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.match2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.match2.setGeometry(QtCore.QRect(610, 320, 141, 31))
        self.match2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.match2.setText("")
        self.match2.setObjectName("match2")
        GAME.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=GAME)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        GAME.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=GAME)
        self.statusbar.setObjectName("statusbar")
        GAME.setStatusBar(self.statusbar)

        # Game state initialization
        self.main_window = GAME
        self.count1 = 0
        self.count2 = 0
        self.user1_matched = False
        self.user2_matched = False

        # Initial UI state: only User 1 enabled
        self.u2guess.setEnabled(False)
        self.input2.setEnabled(False)

        # Connect signals
        self.U1guess.clicked.connect(self.handle_u1_guess)
        self.u2guess.clicked.connect(self.handle_u2_guess)
        self.Restart_button.clicked.connect(self.restart_game)
        self.EXIT_button.clicked.connect(self.main_window.close)

        self.retranslateUi(GAME)
        QtCore.QMetaObject.connectSlotsByName(GAME)

    def handle_u1_guess(self):
        val = int(self.input1.value())
        b = random.randint(1, 6)
        self.system1gen.setText(str(b))
        self.count1 += 1
        self.Score1.setText(str(self.count1))
        if val == b:
            self.match1.setText("Yes")
            self.user1_matched = True
            self.U1guess.setEnabled(False)
            self.input1.setEnabled(False)
            # Enable user 2
            self.u2guess.setEnabled(True)
            self.input2.setEnabled(True)
            self.Result.setText(f"User 1 matched in {self.count1} attempts. Now User 2's turn.")
        else:
            self.match1.setText("No")
            self.Result.setText("User 1: Not matched, try again.")

    def handle_u2_guess(self):
        val = int(self.input2.value())
        b = random.randint(1, 6)
        self.system2Gen.setText(str(b))
        self.count2 += 1
        self.score2.setText(str(self.count2))
        if val == b:
            self.match2.setText("Yes")
            self.user2_matched = True
            self.u2guess.setEnabled(False)
            self.input2.setEnabled(False)
            # Determine winner
            if self.count1 < self.count2:
                self.Result.setText("User 1 guessed earlier than User 2 — User 1 wins")
            elif self.count1 == self.count2:
                self.Result.setText("User 1 and User 2 guessed in same time. Draw")
            else:
                self.Result.setText("User 2 wins")
        else:
            self.match2.setText("No")
            self.Result.setText("User 2: Not matched, try again.")

    def restart_game(self):
        # Reset state and UI
        self.count1 = 0
        self.count2 = 0
        self.user1_matched = False
        self.user2_matched = False
        self.system1gen.setText("")
        self.system2Gen.setText("")
        self.Score1.setText("")
        self.score2.setText("")
        self.match1.setText("")
        self.match2.setText("")
        self.Result.setText("User 1's turn. Guess a number (1-6).")
        self.U1guess.setEnabled(True)
        self.input1.setEnabled(True)
        self.u2guess.setEnabled(False)
        self.input2.setEnabled(False)

    def retranslateUi(self, GAME):
        _translate = QtCore.QCoreApplication.translate
        GAME.setWindowTitle(_translate("GAME", "MainWindow"))
        self.label_3.setText(_translate("GAME", "WORD GUESSING GAME"))
        self.label_8.setText(_translate("GAME", "User 1"))
        self.label_9.setText(_translate("GAME", "User 2"))
        self.numlabel.setText(_translate("GAME", "Enter Number :"))
        self.Restart_button.setText(_translate("GAME", "RESTART"))
        self.EXIT_button.setText(_translate("GAME", "EXIT"))
        self.RESULTLABEL.setText(_translate("GAME", "RESULT :"))
        self.U1guess.setText(_translate("GAME", "Guess"))
        self.label_12.setText(_translate("GAME", "System Generates :"))
        self.label_14.setText(_translate("GAME", "Attempts :"))
        self.label_16.setText(_translate("GAME", "Status :"))
        self.label_18.setText(_translate("GAME", "Matched :"))
        self.numlabel2.setText(_translate("GAME", "Enter Number :"))
        self.u2guess.setText(_translate("GAME", "Guess"))
        self.label_20.setText(_translate("GAME", "System Generates :"))
        self.label_23.setText(_translate("GAME", "Status :"))
        self.label_24.setText(_translate("GAME", "Attempts :"))
        self.label_26.setText(_translate("GAME", "Matched :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GAME = QtWidgets.QMainWindow()
    ui = Ui_GAME()
    ui.setupUi(GAME)
    GAME.show()
    sys.exit(app.exec())
